### ISSUE TITLE
Ages (in parenthesis) not updating/not removed after removing year from contact's birthday

### ISSUE THREAD

**Issue by larryb31** [PrivacyApps/birthday-calendar#79]
Hi, great app! 
A bug - I removed the year and left just the month and day in the birthday - but the app is still showing the 'age' in parenthesis.
Thanks
Larry

**Comment by MarkGri** [comment]
Same problem here. Sometimes I don't know someone's year of birth and just enter the day and month. Then the age is always shown as (45)! Seems the default year is 1970. Better to use the current year as default and show age as (0), out better still as blank in this case. Otherwise a very nice app. Thanks, Mark

**Comment by amitkeret** [comment]
Same here.
Pretty sure the problem is the app calculates according to 1970 is the birth year is not set.
Should remove the parentheses is no year was set, IMO.

This bug and also #52 are pretty old... Any plans to fix this?

**Comment by gigan3rd** [comment]
01.01.1970 sounds like a fallback date. For example, it also sets current date to 01.01.1970 when the system date gets reset (pull out battery without proper shutdown and reboot) because when it wouldn't do that, I imagine an exception would occur or some weird error would be shown. *Therefore, it's not a bug, it's a feature.*
A workaround is needed: Either don't show the age when a contact is born in 1970 (which might not be an option because there are people born in this year) or don't process birthdays without years at all, means, don't create events for them. If I think about it, a calendar app would expect a year to show events in the correct year. Also, the calculations done in the code would never succeed without a proper year. :D

I could definitely experiment a bit with that but the contacts apps of all the Android phones I can use force me to enter a year between 1900 and 2100, therefore it's never empty. How exactly do you remove the year, or which app do you use to enter birthdays?

**Comment by amitkeret** [comment]
I'm using the built-in contacts/people app on Android. When I add an event date, the option comes up.
See screenshots from Android [4.3.1](http://imgur.com/NHKoSTE) and [5.1.1](http://imgur.com/LafcdF8).

**Comment by dschuermann** [comment]
@amitkeret I think this feature has been removed in Android 6. At least I no longer have the checkbox on Nexus 6P with vanilla Android 6 and a caldav account using davdroid.

**Comment by dschuermann** [comment]
*woops* accidental close

**Comment by amitkeret** [comment]
@dschuermann can you make sure?
You can, for example, go to your Google contacts through Gmail ("g c" shortcut) and add a birthday through there. I know for a fact that you can add birthdays without years. Then, check what happens in your Andoid contacts.

**Comment by middelheim** [comment]
(CopperheadOS) Android 7.0.1 , the Contacts app unchanged from AOSP

In the Contacts app, edit a Contact, tap the date field,  there is a checkbox where I can choose to include the year or not. I made some fine screenshots but seem not to be able to upload them here, maybe because my github account is brand new. 

This bug is very unfortunate because most contacts will have their 47th birthday this year according to birthday adapter :)

If you need the screenshots I can mail them, let me know.

**Comment by jondo** [comment]
Same as middelheim here on LineageOS 14.1, i.e. Android 7.1.2.
The app settings even allow custom formatting for dates without year, but that case is not recognized.
